server {
    listen 80;
    server_name minecraft.home;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name minecraft.home;

    ssl_certificate /etc/nginx/certs/home.local.crt;
    ssl_certificate_key /etc/nginx/certs/home.local.key;

    resolver 127.0.0.11 valid=30s ipv6=off;

    set $minecraft_web http://ghms-frontend:80;

    location / {
        proxy_pass $minecraft_web;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}